### ISSUE TITLE
I used to clone on the green button 

### ISSUE THREAD

**Issue by thisis-Solomon** [bongohive-internship/portfolio-thisis-Solomon#1]
I need help on this please where you said clone the repo git clone https://github.com/BongoHive/reponame.git my-portfolio
warning Please replace reponame in the above link ☝🏾 with the name of this repo

**Comment by Mulency** [comment]
Hello,
It is telling you to replace "reponame.git" in " https://github.com/BongoHive/reponame.git " with the actual name of the repo you want to clone

**Comment by thisis-Solomon** [comment]
what happens if i just clone from the green button?

**Comment by Mulency** [comment]
Please do the recommended read up on how to use git in the resources provided. This is part of the challenge for you to solve.
